[build]
target = "i486-dos"
rustflags = ["-Zunstable-options", "-Cdebuginfo=0"]

[unstable]
build-std = ["core"]
json-target-spec = true

[target.i486-dos]
runner = ["cargo-dos", "postlink"]

[env]
RUST_TARGET_PATH = "/home/Source/github/cremorlian/rust-dos/target/x86_64-unknown-linux-gnu/debug/cargo-home/rust-dos"
